# FILE: src/lib/core/config.sh
#!/usr/bin/env bash
# FlashFind Core Configuration
FLASHFIND_VERSION="1.0.0"; FLASHFIND_DIR="${HOME}/.flashfind"; HISTORY_FILE="${FLASHFIND_DIR}/history"
CACHE_DIR="${FLASHFIND_DIR}/cache"; CONFIG_FILE="${FLASHFIND_DIR}/config"
mkdir -p "${FLASHFIND_DIR}" "${CACHE_DIR}"; touch "${HISTORY_FILE}"
if [ ! -f "${CONFIG_FILE}" ]; then
  cat > "${CONFIG_FILE}" << 'EOL'
# FlashFind Configuration
FLASHFIND_DEBUG=0
FLASHFIND_USE_FUZZY=1
FLASHFIND_MAX_HISTORY=20
FLASHFIND_VIBE_MODE=0
FLASHFIND_USE_COLOR=1
EOL
fi
source "${CONFIG_FILE}"
: "${FLASHFIND_DEBUG:=0}" "${FLASHFIND_USE_FUZZY:=1}" "${FLASHFIND_MAX_HISTORY:=20}" "${FLASHFIND_VIBE_MODE:=0}" "${FLASHFIND_USE_COLOR:=1}"

